# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Gradle wrapper and project files
COPY gradle /app/gradle
COPY gradlew /app/gradlew
COPY build.gradle /app/build.gradle
COPY settings.gradle /app/settings.gradle
COPY src /app/src

# Give the Gradle wrapper execute permission
RUN chmod +x /app/gradlew

# Build the application using Gradle
RUN ./gradlew build --no-daemon

# Copy the JAR file from the build directory
COPY build/libs/payment-1.0.0.jar  /app/payment-1.0.0.jar

# Expose the port your application will run on
EXPOSE 8080

# Define the command to run your application
CMD ["java", "-jar", "/app/payment-1.0.0.jar"]
